Feature: Enable Kafka integration
parseablehq/parseable pull request #1021
Opened 2024-12-05 03:56 UTC by parmesant

Fixes #936

For this to work, these env vars are mandatory-
- `P_KAFKA_TOPIC`
- `P_KAFKA_HOST`
- `P_KAFKA_GROUP`

### Description

<hr>

This PR has:
- [x] been tested to ensure log ingestion and log query works.
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added documentation for new or modified features or behaviors.

2024-12-13 12:58 UTC, de-sh requested changes

2024-12-13 12:58 UTC, de-sh commented on src/kafka.rs
> +    tokio::task::spawn(async move {
moving this to main could be a good idea from a readability standpoint

2024-12-16 05:56 UTC, parmesant commented on src/cli.rs
> +    pub const KAFKA_PARTITIONS: &'static str = "kafka-partitions";
Create a separate issue for this please

2024-12-16 06:27 UTC, parmesant commented
`libz` support has been turned off for now
The other option was to force users to use `libz` which we decided against

2024-12-16 08:32 UTC, de-sh approved these changes

2024-12-20 17:19 UTC, merged