Ingestion partition change
parseablehq/parseable pull request #683
Opened 2024-03-04 18:37 UTC by nikhilsinhacloudsurfex

add custom header X-P-Time-Partition (optional) at stream creation api -- to allow ingestion/query using timestamp column from the log data instead of server time / p_timestamp

store the time_partition field name in stream.json and in memory STREAM_INFO

in ingest api - check if timestamp column name exists in the log data, if no, throw exception
also, check if timestamp value can be parsed into datetime, if no, throw exception

arrow file name gets the date, hr, mm from the timestamp field (if defined in stream) else file name gets the date, hr, mm from the server time

parquet file name gets a random number attached to it -- this is because a lot of log data can have same date, hr, mm value of the timestamp field and with this random number, parquet will not get overwritten

in the console, query from and to date will be matched against the value of the timestamp column of the log data (if defined in the stream), else from and to date will be matched against the p_timestamp column

2024-03-05 12:40 UTC, nitisht commented
Fixes #685

2024-03-05 18:01 UTC, Eshanatnight requested changes

2024-03-06 18:27 UTC, nikhilsinhacloudsurfex commented on server/src/handlers/http/ingest.rs
> +    }
the logic has changed now, please review again

2024-03-07 04:23 UTC, Eshanatnight requested changes
Apart from that one function else LGTM

2024-03-07 05:56 UTC, merged